#!/bin/bash
#PBS -q default
#PBS -N DeepWalk_Output
##serial jobs: only 1 processor core is requested
#PBS -l select=1:mem=64gb:ncpus=1
#PBS -l walltime=72:00:00
#PBS -W group_list=x-ccast-prj-luliu
cd $PBS_O_WORKDIR
deepwalk --format edgelist --input data.txt --max-memory-data-size 0 --number-walks 80 --representation-size 10 --walk-length 40 --window-size 10 --workers 1 --output deepwalk_output.txt
